import React, { useState, useRef, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Bot,
  Sparkles,
  Send,
  User,
  Copy,
  Check,
  RefreshCw,
  FileText,
  TrendingUp,
  Mail,
  Target,
  Shield,
  Lightbulb,
  ArrowRight,
  Zap
} from 'lucide-react';
import { useCrm } from '../context/CrmContext';
import { sendGeminiChatMessage, GeminiChatMessage } from '../services/geminiService';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export const AiAssistantView: React.FC = () => {
  const { customers, leads, tasks, employees, settings, currentUser, addTask, addLead } = useCrm();

  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome-msg',
      role: 'assistant',
      content: `Hello **${currentUser.displayName}**, I am your **TRISHUL AI Executive Consultant**, powered by Google Gemini 2.5 Flash.\n\nI have real-time access to your Firestore database:\n- **${customers.length} Customers** (Active & Enterprise)\n- **${leads.length} Leads** in pipeline\n- **${tasks.length} Assigned Tasks**\n- **${employees.length} Team Members**\n\nHow can I optimize your sales cycle, draft proposals, or analyze team performance today?`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);

  const [inputPrompt, setInputPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const quickPrompts = [
    {
      title: 'Daily Executive Briefing',
      icon: TrendingUp,
      prompt: 'Provide a concise executive summary of today\'s CRM status, highlighting high-value leads, pending tasks due soon, and revenue growth recommendations.'
    },
    {
      title: 'Analyze Pipeline & Follow-ups',
      icon: Target,
      prompt: 'Review the current leads pipeline. Identify which leads have highest potential and write 3 specific follow-up strategies for the sales team.'
    },
    {
      title: 'Draft Client Proposal Email',
      icon: Mail,
      prompt: 'Draft a high-converting enterprise proposal email for our CRM software and consulting services, emphasizing ROI, security, and dedicated support.'
    },
    {
      title: 'Create Follow-up Task',
      icon: Zap,
      prompt: 'Create a high-priority task assigned to Rahul Verma to conduct a product demo for Acme Technologies by tomorrow.'
    }
  ];

  const handleSendMessage = async (textToSend?: string) => {
    const messageText = textToSend || inputPrompt.trim();
    if (!messageText || isLoading) return;

    const userMessage: Message = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: messageText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages(prev => [...prev, userMessage]);
    if (!textToSend) setInputPrompt('');
    setIsLoading(true);

    try {
      // Build CRM context payload
      const crmContextPayload = {
        totalCustomers: customers.length,
        totalLeads: leads.length,
        totalTasks: tasks.length,
        totalEmployees: employees.length,
        sampleCustomers: customers.slice(0, 5).map(c => ({ name: c.name, company: c.company, value: c.value })),
        sampleLeads: leads.slice(0, 5).map(l => ({ name: l.name, company: l.company, status: l.status, value: l.estimatedValue })),
        pendingTasks: tasks.filter(t => t.status !== 'Completed').map(t => ({ title: t.title, assignee: t.assignedUserName, due: t.dueDate })),
      };

      const historyPayload: GeminiChatMessage[] = messages.slice(-8).map(m => ({
        role: m.role,
        content: m.content
      }));

      const replyContent = await sendGeminiChatMessage(
        messageText,
        historyPayload,
        crmContextPayload
      );

      let finalReply = replyContent;

      // Check if user requested creating a task or lead via natural language
      if (messageText.toLowerCase().includes('create') && messageText.toLowerCase().includes('task')) {
        await addTask({
          title: 'AI Scheduled: ' + messageText.substring(0, 40),
          description: 'Auto-generated by Trishul AI Assistant prompt.',
          assignedUserId: 'emp-1',
          assignedUserName: 'Rahul Verma',
          dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
          priority: 'High',
          status: 'Pending',
          category: 'AI Auto-Action'
        });
        finalReply += "\n\n✅ *Action Executed:* I have also automatically created and registered this task in your Tasks dashboard.";
      }

      const assistantMessage: Message = {
        id: `ai-${Date.now()}`,
        role: 'assistant',
        content: finalReply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setMessages(prev => [...prev, assistantMessage]);
    } catch (err: any) {
      const errorMessage: Message = {
        id: `err-${Date.now()}`,
        role: 'assistant',
        content: `Sorry, an error occurred while consulting Gemini AI: ${err.message || 'Server connection error.'}`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Restrict access if not admin
  if (currentUser.role !== 'admin') {
    return (
      <div className="py-20 text-center rounded-3xl bg-white dark:bg-[#0b1023] border border-slate-200 dark:border-slate-800 p-8 shadow-sm">
        <Shield className="w-14 h-14 text-rose-500 mx-auto mb-4" />
        <h3 className="text-xl font-bold text-slate-900 dark:text-white">Admin Privileges Required</h3>
        <p className="text-sm text-slate-400 max-w-md mx-auto mt-2">
          The TRISHUL AI Executive Consultant is restricted to Administrator access. Please switch role in the top navigation bar to access this module.
        </p>
      </div>
    );
  }

  return (
    <div className="h-[calc(100vh-140px)] flex flex-col space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-purple-600 via-indigo-600 to-cyan-500 p-0.5 shadow-lg shadow-purple-500/20 flex items-center justify-center">
            <Bot className="w-5 h-5 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-black text-slate-900 dark:text-white tracking-tight">TRISHUL AI Executive Assistant</h2>
              <span className="px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-400 border border-purple-500/30 text-[10px] font-bold uppercase">
                Gemini 2.5 Flash
              </span>
            </div>
            <p className="text-[11px] text-slate-700 dark:text-slate-300 font-medium">Real-time intelligent reasoning, deal analysis, and workflow automation.</p>
          </div>
        </div>

        <button
          onClick={() => setMessages([messages[0]])}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-semibold border border-slate-200 dark:border-slate-700 transition-colors"
          title="Clear Conversation"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span className="hidden sm:inline">Reset Chat</span>
        </button>
      </div>

      {/* Quick Prompts Carousel */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5 shrink-0">
        {quickPrompts.map((qp, i) => {
          const Icon = qp.icon;
          return (
            <button
              key={i}
              onClick={() => handleSendMessage(qp.prompt)}
              className="p-2.5 rounded-xl bg-white dark:bg-[#0b1023] border border-slate-200 dark:border-slate-800/90 hover:border-purple-500/40 text-left transition-all group flex items-start gap-2.5 shadow-xs"
            >
              <div className="p-1.5 rounded-lg bg-purple-500/10 text-purple-400 group-hover:bg-purple-500 group-hover:text-white transition-colors shrink-0">
                <Icon className="w-3.5 h-3.5" />
              </div>
              <div className="flex-1 truncate">
                <span className="text-xs font-bold text-slate-800 dark:text-slate-200 block truncate group-hover:text-purple-400">
                  {qp.title}
                </span>
                <span className="text-[10px] text-slate-400 block truncate">
                  Click to run
                </span>
              </div>
            </button>
          );
        })}
      </div>

      {/* Messages Scroll View */}
      <div className="flex-1 overflow-y-auto p-4 rounded-2xl bg-white dark:bg-[#080d1f] border border-slate-200 dark:border-slate-800/90 shadow-inner space-y-4">
        {messages.map((msg) => {
          const isUser = msg.role === 'user';

          return (
            <motion.div
              key={msg.id}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}
            >
              {!isUser && (
                <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-purple-600 to-indigo-600 text-white flex items-center justify-center shrink-0 shadow-md">
                  <Bot className="w-4 h-4" />
                </div>
              )}

              <div className={`max-w-[85%] sm:max-w-[75%] rounded-2xl p-4 text-xs leading-relaxed space-y-2 ${
                isUser
                  ? 'bg-gradient-to-r from-cyan-600 to-blue-600 text-white shadow-md rounded-tr-xs'
                  : 'bg-slate-50 dark:bg-[#0f172a] border border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 shadow-sm rounded-tl-xs'
              }`}>
                <div className="flex items-center justify-between gap-2 pb-1 border-b border-black/10 dark:border-white/10 text-[10px] opacity-75 font-semibold">
                  <span>{isUser ? currentUser.displayName : 'TRISHUL AI'}</span>
                  <span>{msg.timestamp}</span>
                </div>

                <div className="whitespace-pre-wrap font-sans text-xs">
                  {msg.content}
                </div>

                {!isUser && (
                  <div className="pt-2 flex justify-end">
                    <button
                      onClick={() => copyToClipboard(msg.content, msg.id)}
                      className="flex items-center gap-1 text-[10px] text-slate-400 hover:text-slate-200 bg-slate-200/50 dark:bg-slate-800 px-2 py-0.5 rounded transition-colors"
                      title="Copy response"
                    >
                      {copiedId === msg.id ? (
                        <>
                          <Check className="w-3 h-3 text-emerald-400" />
                          <span className="text-emerald-400">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3 h-3" />
                          <span>Copy</span>
                        </>
                      )}
                    </button>
                  </div>
                )}
              </div>

              {isUser && (
                <div className="w-8 h-8 rounded-xl bg-slate-700 text-white flex items-center justify-center shrink-0 text-xs font-bold shadow-md">
                  {currentUser.displayName.charAt(0)}
                </div>
              )}
            </motion.div>
          );
        })}

        {isLoading && (
          <div className="flex gap-3 items-center">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-purple-600 to-indigo-600 text-white flex items-center justify-center shrink-0 animate-pulse">
              <Bot className="w-4 h-4" />
            </div>
            <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-[#0f172a] border border-slate-200 dark:border-slate-800 text-xs text-purple-400 flex items-center gap-2">
              <Sparkles className="w-4 h-4 animate-spin text-purple-400" />
              <span>Analyzing CRM pipeline with Gemini AI...</span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Form Strip */}
      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleSendMessage();
        }}
        className="relative flex items-center gap-2"
      >
        <input
          type="text"
          value={inputPrompt}
          onChange={(e) => setInputPrompt(e.target.value)}
          placeholder="Ask AI anything (e.g. 'Summarize today\'s revenue', 'Draft email to TechNova')..."
          className="w-full pl-4 pr-12 py-3 rounded-2xl bg-white dark:bg-[#0b1023] border border-slate-200 dark:border-slate-800 text-xs text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:border-purple-500 shadow-md"
        />

        <button
          type="submit"
          disabled={!inputPrompt.trim() || isLoading}
          className="absolute right-2 p-2 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 disabled:opacity-40 disabled:cursor-not-allowed text-white shadow-md transition-all active:scale-95"
        >
          <Send className="w-4 h-4" />
        </button>
      </form>
    </div>
  );
};
